# Generated by Django 2.2.5 on 2019-10-21 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20191019_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='time_stamp',
            new_name='timestamp',
        ),
    ]
