# Generated by Django 2.2.5 on 2019-10-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20191027_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password1', models.CharField(default='', max_length=50000)),
                ('password2', models.CharField(default='', max_length=50000)),
            ],
        ),
    ]
