# Generated by Django 2.2.5 on 2019-10-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_user_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_details',
            new_name='register',
        ),
    ]
