# Generated by Django 2.2.5 on 2019-10-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20191028_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='password1',
            new_name='confirm_password',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='password2',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='username',
            new_name='user_name',
        ),
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
